apiVersion: v1
kind: ImageStream
metadata:
  annotations:
  name: go
spec:
  tags:
  - annotations:
      description: Build and run Go 1.4 applications
      iconClass: icon-go
      sampleRepo: https://github.com/openshift/golang-ex
      supports: go
      tags: builder,go
    from:
      kind: DockerImage
      name: getupcloud/go-14-centos7:latest
    generation: 4
    importPolicy: {}
    name: "1.4"
  - annotations:
      description: Build and run Go 1.5 applications
      iconClass: icon-go
      sampleRepo: https://github.com/openshift/golang-ex
      supports: go
      tags: builder,go
    from:
      kind: DockerImage
      name: getupcloud/go-15-centos7:latest
    generation: 4
    importPolicy: {}
    name: "1.5"
  - annotations:
      description: Build and run Go 1.6 applications
      iconClass: icon-go
      sampleRepo: https://github.com/openshift/golang-ex
      supports: go
      tags: builder,go
    from:
      kind: DockerImage
      name: getupcloud/go-16-centos7:latest
    generation: 4
    importPolicy: {}
    name: "1.6"
  - annotations:
      description: Build and run Go applications
      iconClass: icon-go
      sampleRepo: https://github.com/openshift/golang-ex
      supports: go
      tags: builder,go
    from:
      kind: ImageStreamTag
      name: "1.6"
    generation: 1
    importPolicy: {}
    name: latest
